m1 = int(input("enter markes of student no 1 : "))
m2 = int(input("enter markes of student no 2 : "))
m3 = int(input("enter markes of student no 3 : "))
m4 = int(input("enter markes of student no 4 : "))
m5 = int(input("enter markes of student no 5 : "))
m6 = int(input("enter markes of student no 6 : "))
myList = [m1, m2, m3, m4, m5,m6]
# myList.sort()
myList.reverse()
print(myList)